
CREATE TABLE Roles (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE UserStatus (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Code VARCHAR(3) NOT NULL UNIQUE,
    Description VARCHAR(50) NOT NULL
);
GO

CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    
    RoleId INT NOT NULL,
    StatusId INT NOT NULL,

    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,

    CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id),
    CONSTRAINT FK_Users_Status FOREIGN KEY (StatusId) REFERENCES UserStatus(Id)
);
GO

CREATE TABLE Menu (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Route VARCHAR(100) NOT NULL,
    Icon VARCHAR(50) NULL,
    [Order] INT NOT NULL,
    ParentId INT NULL,
    IsActive BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_Menu_Parent FOREIGN KEY (ParentId) REFERENCES Menu(Id)
);
GO

CREATE TABLE RoleMenu (
    RoleId INT NOT NULL,
    MenuId INT NOT NULL,

    PRIMARY KEY (RoleId, MenuId),

    CONSTRAINT FK_RoleMenu_Role FOREIGN KEY (RoleId) REFERENCES Roles(Id),
    CONSTRAINT FK_RoleMenu_Menu FOREIGN KEY (MenuId) REFERENCES Menu(Id)
);
GO

